### ISSUE TITLE
It only uploads microg.

### ISSUE THREAD

**Issue by ronin08** [n0k0m3/revanced-build-template#46] opened 2022-07-21 10:20 UTC

**Comment by n0k0m3** [comment] 2022-07-21 12:00
Can't reproduce due to insufficient info

**Comment by ronin08** [comment] 2022-07-21 13:20
You can see here (https://github.com/ronin08/revanced-build-template) yourself. I have just edited the patches.txt file.

**Comment by ManorSailor** [comment] 2022-07-23 06:08
> You can see here the log of workflow(https://github.com/ronin08/revanced-build-template) yourself. I have just edited the patches.txt file.

I see. Thank you for reporting the issue, it has been fixed in #48. However, I agree with @n0k0m3, please if you create an issue try to provide as much information as you can. If nothing, please link the logs of github actions
I had to go through your repository to see the logs & your commit history.

The reason why your build broke is because you have an extra whitespace near the end of patches.txt, now this isn't your fault. I as contributor could have been more cautious & thought about edge cases. Anyway, now thanks to you, I was able to catch this edge case & fix it.
Now the script won't break even if you added whitespace or tabs on purpose :P

On a side-note, you do not need to include patches which are included in ReVanced CLI by default, i.e, amoled, disable-create-button etc The section to include patches is only for patches which should be explicitly included.

A small list of those patches can be found in the example section of [Patches guide](https://github.com/n0k0m3/revanced-build-template/blob/main/PATCHES_GUIDE.md#example) 
For a full list of these patches, you should look at official ReVanced patches repository.

Btw, @n0k0m3 we should update the Patches guide to include this information since many users will think they have to include all patches.

**Comment by ronin08** [comment] 2022-07-23 07:09
There is no mention of specific patches that need to be explicitly included in official repository too.
If you find, please send here.

**Closed** 2022-07-23 07:40 UTC
